### ISSUE TITLE
Add Single swipe up Gesture

### ISSUE THREAD

**Issue by GocalSD** [rgocal/GCA_LAUNCHER#9]
*Sent by [**raufk275@gmail.com**](mailto:raufk275@gmail.com)*

Description:
---

Right now with GCA launcher  its very annoying to get the app drawer.
A single swipe would be awesome to get the app drawer.
Please sir review my suggestion.

Device info:
---
<table>
<tr><td>App version</td><td>2.00 (12) beta</td></tr>
<tr><td>App version code</td><td>40</td></tr>
<tr><td>Android build version</td><td>eng.bart.20200308.215148</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QQ2A.200305.003</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>vince</td></tr>
<tr><td>Device model</td><td>Redmi 5 Plus</td></tr>
<tr><td>Device product name</td><td>revengeos_vince</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>Summary Report</td><td>true</td></tr>
<tr><td>GCA V2</td><td>Pre-Beta</td></tr>
</table>

**Comment by rgocal** [comment]
Added fine tuning option in app drawer options
